### ISSUE TITLE
[Request] Math Operation with generic typed parameters

### ISSUE THREAD

**Issue by arthurvasconcelos** [RealityStop/Bolt.Addons.Community#1]
![image](https://user-images.githubusercontent.com/1286768/44185076-9952d700-a0e8-11e8-8b6a-b5a3637453c2.png)

In the situation above I can't use math operations because it only accept float parameters, but I can for example multiply a vector3 with a float and the output will be a new vector3.

**Comment by RealityStop** [comment]
![image](https://user-images.githubusercontent.com/33366270/45663851-b0fdf080-bad6-11e8-9ff8-6f5faa4841bf.png)

It took me a month, but I got there.
