### ISSUE TITLE
Comment's Colour bugged

### ISSUE THREAD

**Issue by AiSard** [RealityStop/Bolt.Addons.Community#11]
The Comment node's Colour option is bugged. 

The colour-space seems to be red-green-alpha or some such.

(Also, could we also change the colour for Todo nodes?)

**Comment by RealityStop** [comment]
Sorry for missing this, somehow my email notifications are off and I've been putting the addons on ice until Bolt 2 gets a bit more stable, so I hadn't manually checked in.

Yes, the color is.... odd.  Unfortunately, I don't have control over that :-(.  Bolt is asking for a color, and I'm giving it back the user specified color, but it's blending channels internally. Thanks for the reminder, though, I'll ask Lazlo if he can add support for fully user specified colors.

**Comment by RealityStop** [comment]
What color would you like for the Documentation nodes?  I just tried for a color that didn't overlap with an existing color usage.

**Comment by AiSard** [comment]
That's fine (also forgot about this as well) saw your reaction on #beginner-help :P

Ah, sorry was unclear.
Meant that I wish all Documentation Node colours could be changed.
That way you could categorize types of Comments and Todo urgency for instance.
Current default is fine.

**Comment by JasonJonesLASM** [comment]
I've worked on updating the comments entirely. I'm thinking of making the drag area bigger. This solves the color problem, by drawing the background style and behavior myself, and differentiates comments from units better.

Thoughts?

![unknown](https://user-images.githubusercontent.com/7036136/124312531-75285e80-db3d-11eb-8cd3-159195e30692.png)

If everyone is in agreeance, I'll close this issue and commit the change to the UVS dev branch.

**Comment by JasonJonesLASM** [comment]
Finalized in the new branch.
