### ISSUE TITLE
Crash when trying to add a comment unit

### ISSUE THREAD

**Issue by TowerCrow** [RealityStop/Bolt.Addons.Community#16]
Not sure if this is related to community addon unit "Comment" or not but my Unity editor crashed right after I added the unit (or at least tried to). The crash happened right after I clicked on the "Comment" unit in the fuzzy finder. I also can't reproduce the issue but I have the crash log:

https://cdn.discordapp.com/attachments/377920378426884110/539561622557949993/Crash_2019-01-28_213900608.zip

**Comment by RealityStop** [comment]
this has never been duplicated.  I'm not discounting it, but it's been two years without another report of it.   :-)
