### ISSUE TITLE
TypeLoadException error when bringing in fundamentals to new project

### ISSUE THREAD

**Issue by Jonathan-Turner** [RealityStop/Bolt.Addons.Community#17]
Hello,

Unity version: 2019.2.7f2 Personal
Bolt version: 1.4.7
Bolt.Addons.Community version: 2.4

I am not sure if this is just a version mismatch or what, I see that somebody has a branch open  to update the version of bolt referenced by the package.

In the event that something else might be going on, throwing this up here.

Error received when trying to `Build Unit Options` in a nearly fresh unity project:
![image](https://user-images.githubusercontent.com/6035179/66255083-15710980-e745-11e9-9c3b-755b170ef0a2.png)

**Comment by RealityStop** [comment]
Fixed in 2.4.1!

https://github.com/RealityStop/Bolt.Addons.Community/releases/tag/2.4.1
