### ISSUE TITLE
Prototype events

### ISSUE THREAD

**Issue by RealityStop** [RealityStop/Bolt.Addons.Community#19]
Prototyping events are like Manual Events, but are globally registered and shown in an editor window that allows triggering them.   (Obviously there is no way to trigger them in a built project, but they can be used to assist with forcing or triggering behaviors during production.)

**Comment by JasonJonesLASM** [comment]
This essentially can be done via the newer, Editor Window Asset, using an If node, connected with a GUILayout.Button. Plus you can customize it to your liking, and it remains seperate from runtime graphs. Imo, this isn't that beneficial with that in mind. Feel free to reopen if you disagree.
