### ISSUE TITLE
Event names not fully visible in drop-down

### ISSUE THREAD

**Issue by twiddles** [RealityStop/Bolt.Addons.Community#20]
When using DefinedEvents (On Event and Triggers) the drop-down is too small to display the full event name. One can only see the beginning of the name. It would be great if the combo box extended to to a width where the whole event name is visible.

If possible (at all) given the GUI framework Bolt is using, I'd be happy to contribute. Any pointers into the right direction would be appreciated.
![image](https://user-images.githubusercontent.com/242461/78168145-b79d5000-744f-11ea-9735-cca6bcfef453.png)

**Comment by JasonJonesLASM** [comment]
There have been some long standing issues, and I am trying to fix them and move forward with all the new goodies. Sorry we didn't reply. Editor stuff is more my forte. 

I removed the Event Type label on the headers only and it improves it. This is in the UVSsupport-Dev branch, for next release. This can be added back in if it truly helps everyone, but I think it maintains better readability and cleanliness. You can see what that value is when selecting a unit and looking in the inspector, already. 

![Unity_2021-07-02_16-38-42](https://user-images.githubusercontent.com/7036136/124326279-24703000-db54-11eb-947a-9cbf98221733.png)

It is indeed possible to do that by working on the widget for the unit though. Using GUI.skin.label.CalcWidth you can feed in the name of the type and get its width, and feed that into the header width override I believe.
