### ISSUE TITLE
Get Nested Child Node

### ISSUE THREAD

**Issue by RealityStop** [RealityStop/Bolt.Addons.Community#23]
A request popped up on the discord server:

![image](https://user-images.githubusercontent.com/33366270/97579054-fab0a900-19c7-11eb-9d43-38a470601c7e.png)

**Comment by RealityStop** [comment]
My initial thoughts is this approach is fragile -  a simple reorganization of your hierarchy shouldn't invalidate your code, and I'm not sure that promoting this approach is healthy for new users.  However the node would be easy to write.

Thoughts?

**Comment by BlindsidedGames** [comment]
I don’t disagree with you but what about if you have a graph in a prefab and in that prefab you have a ton of child objects what would a better way than get child’s is there?

**Comment by BlindsidedGames** [comment]
https://i.imgur.com/rrkwJSo.png

**Comment by BlindsidedGames** [comment]
This would indeed work for movability in hierarchy but I'm still keen on having the nested get childs

**Comment by BlindsidedGames** [comment]
[https://i.imgur.com/iGxaecX.png](url)

**Comment by BlindsidedGames** [comment]
Consider this redundant and me stupid

**Comment by RealityStop** [comment]
Setting event sources happens whenever the graph activates.  In the case of a Flow Machine, that's on Awake, I believe.  In the case of a state graph, it's whenever the state becomes active.

Another way you could handle this is use an object variable, with a GameObject/Transform/Whatever type.  Because this is a child of the asset, even if you are using a macro, you'll be able to store references to the prefab's children.  If you're using prefab variants, they'll all get the variable too, so you only have to set it once.

**Comment by BlindsidedGames** [comment]
Isn’t get child done whenever it’s called though? I feel like I would still prefer it even if just for the ability to change it during runtime

**Comment by RealityStop** [comment]
In that case I was referring to the example where the GetChild chain was feeding into an event target, which is only run once when the event listener is set up.  If it's in the flow coming out of the event, then yes, it is run each time.

You can change variables at runtime too, and are probably the best fit for referring to deep child members at runtime.  I know Bolt kind of hammers into your head that you can't store object references in Macros, but you can.  You can't store *SCENE* object references, but references to other objects within the prefab will serialize just fine.
