### ISSUE TITLE
2018.4.28f1 missing assembly's 

### ISSUE THREAD

**Issue by Xulain** [RealityStop/Bolt.Addons.Community#26]
I cant use higher than unity 2018 because I'm developing for sinespace and the community addons has 92  missing assembly's errors that won't clear. I need bolt to make tools so without manual triggers I can't use it.

**Comment by Xulain** [comment]
https://prnt.sc/vtgj9i

**Comment by RealityStop** [comment]
![image](https://user-images.githubusercontent.com/33366270/101292275-70d0d880-37dc-11eb-9f6e-c2212cac4fcc.png)

This is an issue in pre-2019.3, where the import settings for the asmdef are not properly resolved.  This might just be a manual step, I need to look into why the assembly didn't resolve.
