### ISSUE TITLE
[2020.2] ManualEvent trigger button doesn't appear

### ISSUE THREAD

**Issue by bguyl** [RealityStop/Bolt.Addons.Community#29]
### Version

* Unity 2020.2.1f1
* Bolt 1.4.13
* Community Addons 3.0.0 (UPM on master [119ecfa](https://github.com/RealityStop/Bolt.Addons.Community/commit/119ecfa151f2e77dab93035bad0697ee20e5b48a) )

I tested a simple project with just Bolt and Community
* Unity 2019.4.17f1 works fine ✅
* Unity 2020.1.17f1 works fine ✅
* Unity 2020.2.1f1 doesn't work ❌
* Unity 2021.1.0b1 doesn't work ❌

**Comment by RealityStop** [comment]
Thanks for letting us know!

**Comment by bguyl** [comment]
The true Bolt version was `1.4.12`, the version shown in the PackageManagerUI was misleading
After updating Bolt, the issue was fixed
