### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Naani6** [RealityStop/Bolt.Addons.Community#32]
When the package manager import the package he throw this error
![err](https://user-images.githubusercontent.com/54766685/113473208-bd69af00-9470-11eb-846a-504cd8cdeb11.PNG)

**Comment by RealityStop** [comment]
Yep!  Unity came out with a new Bolt version a few days ago, and we had to change the implementation to match the new update.  If you update you Bolt version to 1.4.15, the error should disappear!

If updating Bolt isn't an option, you can use the custom url:

https://github.com/RealityStop/Bolt.Addons.Community.git#Bolt-1.4.13

when importing instead.  As of right now, the old branch isn't missing anything from the main branch

**Comment by Naani6** [comment]
Thank u it's work
