### ISSUE TITLE
Compatibility with Visual Scripting introduced in Unity 2021

### ISSUE THREAD

**Issue by GeorgesGraire** [RealityStop/Bolt.Addons.Community#33]
The community addons are not compatible with the new Visual Scripting feature. Bolt units are now be natively supported with this 2021 feature, but the Community Addons are not.

**Comment by RealityStop** [comment]
The Community addons fully support UnityVS, but it is a different url to add it to the package manager.

![image](https://user-images.githubusercontent.com/33366270/114032128-042d1f80-984a-11eb-87bf-f0f4fdac0db8.png)

This should fully support the released 1.5.1-pre3.  The 1.6.0-pre.3 pre-release version is not yet supported, as the code changes required to support it are not compatible with the released version, but it will be fully supported when the time comes.


Eventually, the master branch (what you get with the default url) will swap to UnityVS, when that is fully released and becomes the standard, but we aren't there yet.

**Comment by BlindsidedGames** [comment]
> The Community addons fully support UnityVS, but it is a different url to add it to the package manager.
> 
> ![image](https://user-images.githubusercontent.com/33366270/114032128-042d1f80-984a-11eb-87bf-f0f4fdac0db8.png)
> 
> This should fully support the released 1.5.1-pre3. The 1.6.0-pre.3 pre-release version is not yet supported, as the code changes required to support it are not compatible with the released version, but it will be fully supported when that is released.
> 
> Eventually, the master branch (what you get with the default url) will swap to UnityVS, when that is fully released and becomes the standard, but we aren't there yet.

can I just point out that this url isnt on the front page

**Comment by GeorgesGraire** [comment]
Thank you @RealityStop!

Indeed as @BlindsidedGames noticed, it is not available on the front page, which make it hard to find!
