### ISSUE TITLE
Query Unit Cannot be invoked in a Super Unit

### ISSUE THREAD

**Issue by JasonJonesLASM** [RealityStop/Bolt.Addons.Community#34]

**Comment by RealityStop** [comment]
Typically this is because there are private variables in use that needs to be shifted over to unit data so it is per-flow, rather than per unit instance.

(you probably already know this)

**Comment by JasonJonesLASM** [comment]
Excellent. I'll look into it. I've actually never used the Data before.

**Comment by JasonJonesLASM** [comment]
Fixed this because I didn't convert the flow to a new flow AsReference, when inside the lambda expressions.
