### ISSUE TITLE
"Not valid JSON"

### ISSUE THREAD

**Issue by VoydVoyd** [RealityStop/Bolt.Addons.Community#40]
Tried on 2019.4.28f1 and 2020.3.19f1.

When I try to use UPM to install, i get the following:

> Cannot perform upm operation: Unable to add package [https://github.com/RealityStop/Bolt.Addons.Community.git]:
>   The file [C:\Users\Billy\Desktop\Unity Projects\Appease\Appeasal\Library\PackageCache\@3da2a809c3\package.json] is not valid JSON:
>     Unexpected string in JSON at position 116 while parsing '{
>     	"name": "dev.bolt.addons",
>     	"versio' [NotFound]
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

Also, I tried downloading the package by cloning the repo, and it apparently relies on references to unity visual scripting namespaces? i thought this was still compatible with pre-2021 versions.

**Comment by JasonJonesLASM** [comment]
Yeah I see the package is missing a comma. Sorry about that. Fix is incoming.

**Comment by JasonJonesLASM** [comment]
Also yes, if your using Bolt, not UVS, use the branch bolt-main. You won't get anything new though. It's too outdated for new stuff. But if you are on UVS, this will work on any version of Unity that Unity Visual Scripting works on.
