### ISSUE TITLE
Consider having two themes, one with less information, like here . . .

### ISSUE THREAD

**Issue by charlesmlamb** [RealityStop/Bolt.Addons.Community#45]
Really like Bolt, want to use it, to learn C#, but there's simply a bunch of information, that I don't need, as a fairly good coder, not looking to replace current theme, but I'd like an alternative, like this . . .

<img width="893" alt="2021-10-09 1450" src="https://user-images.githubusercontent.com/83387915/136658568-61a4d91c-3c21-486b-be9c-8bcc351af40f.png">

Also, the weird orbs, on the side, of the nodes, doesn't really add any useful information, my hope is we can get a more ' compressed ' theme, like shader graph, at least have it, as a customization option . . . The current theme is really good, but I don't need the icons, in the boxes, for instance, just takes up space, for me, I just need a more simple, compressed version, as, an alternative, possibly, just as a theme, in some global setting, or so . . .

![2021-09-23 0901](https://user-images.githubusercontent.com/83387915/136658622-c84bab45-6ab6-47a8-b153-e542516b102c.jpg)

I hope you'll look into making a more sleak UI, to go alongside the current one, also I don't need the animations, while it is running, sort-of, the animated logic lines, it prob. just takes processing power, I don't know if this is possible, but having two options, would help span range, of almost not visual coders, to very visual coders, thanks . . . .

The current theme is actually really good, esp. for beginners, but as someone that has used visual script, for almost two years, it sort-of becomes redundant, hope you might make two themes, or so, or a setting, to not show icons, for instance, in the boxes, to save space, so on . . :OO 

But, at same time the current one, is by now, sort-of a classic, I hope we can just get some options, to customize, the look of the graph, esp. towards simplicity, but one could add even more, on a theme say slider, or so . . . Thx . . .

![2021-10-09 1456](https://user-images.githubusercontent.com/83387915/136658726-bfe4c8fc-72ce-42ff-9715-57f229434bb1.jpg)

I think many users, really like the current theme, I've been thinking, a big group of people, that might get more into game - dev, could be girls, if they're not the most logical thinkers, having a less logical code system, I think will allow many more people to use the engine, so I think there needs to be themes, also, the current one is a master-piece, anyway, please just consider it, if anything, at all, can be done <3 . .

**Comment by JasonJonesLASM** [comment]
I'm sorry but these are better sent to Unity themselves. Maybe try posting all this into the Visual Scripting forum of theirs? Unfortunately pretty much everything you listed here is impossible as just an extender, and needs direct source changes. It's not possible to do stuff to every node but our own, and not possible to edit already existent behavior of the graph.

Thank you for taking the time to do such an extensive write up. Hope you'll share with Unity!
