### ISSUE TITLE
Unity 2021.2 IAotStubbable.GetAotStubs(HashSet<object>) Breaking Bug

### ISSUE THREAD

**Issue by jrDev1** [RealityStop/Bolt.Addons.Community#47]
Hey,

This is broken in new Unity 2021.2 with this error:

`Library/PackageCache/dev.bolt.addons@1ab14307d9/Editor/Windows/View/EditorWindowView.cs(13,58): error CS0535: 'EditorWindowView' does not implement interface member 'IAotStubbable.GetAotStubs(HashSet<object>)'
`

Please fix ASAP!

Thanks,
crafTDev

**Comment by JasonJonesLASM** [comment]
Fixed
