### ISSUE TITLE
Cannot Access Namespace Made in Class Asset

### ISSUE THREAD

**Issue by CG-Tespy** [RealityStop/Bolt.Addons.Community#60]
For context, I have a class asset called TargetSelectStart with its Category set to RPG.UI. Naturally, that means that when compiled, that class is put into the RPG.UI namespace. The thing is that despite my C# scripts referencing the community addons assembly, I can't access the RPG.UI namespace (and by extension, TargetSelectStart).

What I wanted to do was have my C# scripts listen for when events of that class type are triggered, so yeah.

**Comment by S2NX7** [comment]
are you sure you dont have you own assemblies that the scripts are in or your scripts are in a editor folder

**Comment by CG-Tespy** [comment]
Yes, I do have my scripts in their own assembly. I made sure to have it reference the community addons assembly too

**Comment by S2NX7** [comment]
How are you trying to access them?

**Comment by CG-Tespy** [comment]
Through this line of code:
`using RPG.UI;`

As the addon classes are in their own assembly, there was no way for me to access them without making an assembly for my main scripts that references that of the addons.
