### ISSUE TITLE
[Feature Request] Allow Initializing an Object Pool with a Parent of the Client's Choice

### ISSUE THREAD

**Issue by CG-Tespy** [RealityStop/Bolt.Addons.Community#62]
As things are now, all Object Pools do their thing with a parent object that they create. Which is fine for cases where you don't need a specific already-in-the-scene parent for the objects, but for cases you do, they're unusable. 

What would be such a case? The UI for a turn-based RPG. You'd want buttons the player can click to use things like skills or items. Buttons set to specific parents in the UI so that they're placed correctly. Parenting them to some not-in-the-Canvas Transform would make it so that said buttons don't show up, which is... well, yeah.

**Comment by S2NX7** [comment]
Hey well I should be able to add that thanks for letting me know
