### ISSUE TITLE
[Solved] Disabled connection values

### ISSUE THREAD

**Issue by laiqforme** [RealityStop/Bolt.Addons.Community#66]
After installing this asset I have no Connection Values in my graphs. 
Settings Predict Connections Values and Show Connection Values are checked does not work at all.

![Graph 2024-03-13 19 27 19](https://github.com/RealityStop/Bolt.Addons.Community/assets/7236151/c28a1734-588f-47b1-a255-b2e4c37b9fb4)
![Preferences 2024-03-13 19 28 06](https://github.com/RealityStop/Bolt.Addons.Community/assets/7236151/28e8a551-8033-42ac-b51c-3acfa4f95288)

**Comment by laiqforme** [comment]
I have 2 warnings:

Multiple 'Unity.VisualScripting.IWidget' for 'Unity.VisualScripting.ControlConnection'. Ignoring 'Unity.VisualScripting.ControlConnectionWidget'.
UnityEngine.Debug:LogWarning (object)

and

Multiple 'Unity.VisualScripting.IWidget' for 'Unity.VisualScripting.ValueConnection'. Ignoring 'Unity.VisualScripting.ValueConnectionWidget'.
UnityEngine.Debug:LogWarning (object)

**Comment by laiqforme** [comment]
What scripts? SingleDecoratorProvider.cs ?

Here the full log of warning:
Multiple 'Unity.VisualScripting.IWidget' for 'Unity.VisualScripting.ValueConnection'. Ignoring 'Unity.VisualScripting.ValueConnectionWidget'.
UnityEngine.Debug:LogWarning (object)
Unity.VisualScripting.SingleDecoratorProvider`3<Unity.VisualScripting.IGraphItem, Unity.VisualScripting.IWidget, Unity.VisualScripting.WidgetAttribute>:MapAttributeTypes () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Decorators/SingleDecoratorProvider.cs:63)
Unity.VisualScripting.SingleDecoratorProvider`3<Unity.VisualScripting.IGraphItem, Unity.VisualScripting.IWidget, Unity.VisualScripting.WidgetAttribute>:.ctor () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Decorators/SingleDecoratorProvider.cs:23)
Unity.VisualScripting.WidgetProvider:.ctor (Unity.VisualScripting.ICanvas) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Widgets/WidgetProvider.cs:9)
Unity.VisualScripting.VisualScriptingCanvas`1<Unity.VisualScripting.FlowGraph>:.ctor (Unity.VisualScripting.FlowGraph) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Canvases/VisualScriptingCanvas.cs:35)
Unity.VisualScripting.FlowCanvas:.ctor (Unity.VisualScripting.FlowGraph) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Flow/FlowCanvas.cs:13)
System.Reflection.ConstructorInfo:Invoke (object[])
Unity.VisualScripting.TypeUtility/<>c__DisplayClass8_0:<Instantiator>b__1 (object[]) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Runtime/VisualScripting.Core/Reflection/TypeUtility.cs:125)
Unity.VisualScripting.TypeUtility:Instantiate (System.Type,bool,object[]) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Runtime/VisualScripting.Core/Reflection/TypeUtility.cs:154)
Unity.VisualScripting.SingleDecoratorProvider`3<Unity.VisualScripting.IGraph, Unity.VisualScripting.ICanvas, Unity.VisualScripting.CanvasAttribute>:CreateDecorator (System.Type,Unity.VisualScripting.IGraph) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Decorators/SingleDecoratorProvider.cs:32)
Unity.VisualScripting.SingleDecoratorProvider`3<Unity.VisualScripting.IGraph, Unity.VisualScripting.ICanvas, Unity.VisualScripting.CanvasAttribute>:CreateDecorator (Unity.VisualScripting.IGraph) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Decorators/SingleDecoratorProvider.cs:42)
Unity.VisualScripting.SingleDecoratorProvider`3<Unity.VisualScripting.IGraph, Unity.VisualScripting.ICanvas, Unity.VisualScripting.CanvasAttribute>:GetDecorator (Unity.VisualScripting.IGraph) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Decorators/SingleDecoratorProvider.cs:251)
Unity.VisualScripting.XCanvasProvider:Canvas (Unity.VisualScripting.IGraph) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Canvases/CanvasProvider.cs:24)
Unity.VisualScripting.GraphContext`2<Unity.VisualScripting.FlowGraph, Unity.VisualScripting.FlowCanvas>:get_canvas () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Context/GraphContext.cs:30)
Unity.VisualScripting.GraphContext`2<Unity.VisualScripting.FlowGraph, Unity.VisualScripting.FlowCanvas>:Unity.VisualScripting.IGraphContext.get_canvas () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Context/GraphContext.cs:32)
Unity.VisualScripting.GraphWindow:SetReference (Unity.VisualScripting.GraphReference,bool) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Windows/GraphWindow.cs:107)
Unity.VisualScripting.GraphWindow:set_reference (Unity.VisualScripting.GraphReference) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Windows/GraphWindow.cs:74)
Unity.VisualScripting.GraphWindow:MatchSelection (bool) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Windows/GraphWindow.cs:182)
Unity.VisualScripting.GraphWindow:<OnEnable>b__64_0 () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Windows/GraphWindow.cs:335)
Unity.VisualScripting.PluginContainer:add_delayCall (System.Action) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Plugins/PluginContainer.cs:53)
Unity.VisualScripting.GraphWindow:OnEnable () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Windows/GraphWindow.cs:322)
UnityEditor.EditorWindow:GetWindow<Unity.VisualScripting.GraphWindow> ()
Unity.VisualScripting.GraphWindow:OpenActive (Unity.VisualScripting.GraphReference) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Windows/GraphWindow.cs:38)
Unity.VisualScripting.GraphNestEditor:OnEditButtonGUI (UnityEngine.Rect) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/GraphNestEditor.cs:378)
Unity.VisualScripting.GraphNestEditor:OnGUI (UnityEngine.Rect,UnityEngine.GUIContent) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/GraphNestEditor.cs:238)
Unity.VisualScripting.Inspector:Draw (UnityEngine.Rect,UnityEngine.GUIContent) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/Inspector.cs:134)
Unity.VisualScripting.LudiqGUI:Editor (Unity.VisualScripting.Metadata,UnityEngine.Rect) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Interface/LudiqGUI.cs:102)
Unity.VisualScripting.MachineEditor:OnNestGUI (UnityEngine.Rect) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/MachineEditor.cs:81)
Unity.VisualScripting.MachineEditor:OnGUI (UnityEngine.Rect,UnityEngine.GUIContent) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/MachineEditor.cs:54)
Unity.VisualScripting.Inspector:Draw (UnityEngine.Rect,UnityEngine.GUIContent) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/Inspector.cs:134)
Unity.VisualScripting.Inspector:DrawLayout (UnityEngine.GUIContent,single,UnityEngine.RectOffset) (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/Inspector.cs:322)
Unity.VisualScripting.LudiqRootObjectEditor/Individual:OnGUI () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/Root/LudiqRootObjectEditor.cs:52)
Unity.VisualScripting.OptimizedEditor`1<Unity.VisualScripting.LudiqRootObjectEditor/Individual>:OnInspectorGUI () (at ./Library/PackageCache/com.unity.visualscripting@1.9.1/Editor/VisualScripting.Core/Inspection/OptimizedEditor.cs:31)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by S2NX7** [comment]
The FlowEditor script and ValueFlowEditor script

**Comment by laiqforme** [comment]
Thanks! It works!
